#!/usr/bin/env bash

declare -r default_mvn_version=3.0.5
declare -r default_local_dir=${HOME}/.mvnvm
declare mvn_version user_uri user_download_url mirror_download_url archive_download_url binaries_archive_download_url download_file local_dir
declare -a mvn_arguments

echoerr () { [[ -z $quiet ]] && echo "[MVNVM]" "$@" >&2; }
debug()    { [[ -n $debug ]] && echoerr "$@"; }

# process properties for output settings
for arg in "$@"; do
  case $arg in
    -q|--quiet) quiet=true ;;
    -d|--debug) debug=true ;;
    *) ;;
  esac
done

addMvnArgument() {
  debug "add mvn_argument: $1"
  mvn_arguments=( "${mvn_arguments[@]}" "$1" )
}

process_user_defaults()
{
  if [[ -f ~/.mvnvm.properties ]]; then
    . ~/.mvnvm.properties
  fi
}

process_project()
{
  if [[ -f mvnvm.properties ]]; then
    . mvnvm.properties
  elif project_mvn_version="$(ruby <<"EOR"
#!/usr/bin/ruby -w

require 'rexml/document'
include REXML

pomfile = ARGV.concat( ['pom.xml'] )[0]

if !File.file?(pomfile)
  exit 5
end

xmldoc = Document.new(File.new(pomfile))

enforcerVersion = XPath.first(xmldoc, '/project/build/plugins/plugin[artifactId="maven-enforcer-plugin"]//configuration/rules/requireMavenVersion/version')

if enforcerVersion
  # A closed lower bound?
  m = enforcerVersion.text.match(/\s*\[([\d\.]+)\s*,.*/)
  if m
    puts m[1]
  # A specific numeric version?
  elsif enforcerVersion.text.match(/^[\d\.]+$/)
    puts enforcerVersion.text
  else
    exit 5
  end
else
  prereq = XPath.first(xmldoc, '/project/prerequisites/maven')
  if prereq
    puts prereq.text
  else
    exit 5
  end
end
EOR
)"; then
    mvn_version="$project_mvn_version"
  fi
}

process_arguments() 
{
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --apache-mirror) user_uri="$2" && shift 2 && debug "set user_uri: ${user_uri}" ;;
      --mvn-version) mvn_version="$2" && shift 2 && debug "set mvn_version: ${mvn_version}" ;;
      -d|--debug) shift ;;
      -q|--quiet) shift ;;
      *) addMvnArgument "$1" && shift ;;
    esac
  done
}

process_defaults()
{
  user_uri=""
  mvn_version=${default_mvn_version}
  local_dir=${default_local_dir}
}

make_url()
{
  uri="$1"
  version="$2"
  version_regex="([0-9]+)" 
  [[ $version =~ ${version_regex} ]]
  major="${BASH_REMATCH[1]}"
  download_file="apache-maven-${version}-bin.zip"
  download_path_url="maven/maven-${major}/${version}/binaries/${download_file}"

  # If the user has provided a URI, append the artefacts download url to it
  if [ -z "$uri" ]; then
    user_download_url=""
  else
    user_download_url="${uri}/${download_path_url}"
  fi

  # archive url is always available, so set that
  archive_download_url="http://archive.apache.org/dist/${download_path_url}"
  # but some old versions are only available at archived binaries path
  binaries_archive_download_url="http://archive.apache.org/dist/maven/binaries/${download_file}"

  # instead of always using archive url, use the recommended apache mirror initially
  if which curl >/dev/null; then
    closer_text=`curl --silent --fail http://www.apache.org/dyn/closer.cgi?asjson=1`
  elif which wget >/dev/null; then
    closer_text=`wget -qO- http://www.apache.org/dyn/closer.cgi?asjson=1`
  fi

  if [ -z "$closer_text" ]; then
    release_download_url=""
  else
    # extract the preferred mirror url from returned 
    # use python if it is available, otherwise fall back to attempt scraping from text
    if which python >/dev/null; then
      temp=`echo $closer_text \
        | python -c 'import sys, json; print json.load(sys.stdin)["preferred"]'`
    else 
      temp=`echo $closer_text \
        | fgrep preferred \
        | cut -f4 -d\"`
    fi

    release_download_url="${temp}${download_path_url}"
  fi
}

execRunner () {
  export MVN_HOME="${local_dir}/apache-maven-${mvn_version}"
  export M2_HOME="${MVN_HOME}"
  export MVN_OPT=""
  exec "$@"
}

prepareDirectories() {
  if [[ ! -d "${local_dir}" ]]; then
    mkdir -p "${local_dir}"
  fi
}

downloadMaven() {
  if [[ ! -f "${local_dir}/${download_file}" ]]; then
    echoerr "            downloading: ${download_file}"
    echoerr "                     to: ${local_dir}/${download_file}"
    
    if [ -z "$user_download_url" ]; then
        # nothing
        true
    else
        echoerr "                 trying: ${user_download_url}"
    fi

    if which curl >/dev/null; then      
      curl --silent --fail "${user_download_url}" --output "${local_dir}/${download_file}" || {
        echoerr "trying preferred mirror: ${release_download_url}"
        curl --silent --fail "${release_download_url}" --output "${local_dir}/${download_file}" || {
          echoerr "falling back to archive: ${archive_download_url}"
          curl --silent --fail "${archive_download_url}" --output "${local_dir}/${download_file}" || {
            echoerr "must be old archive url: ${binaries_archive_download_url}"
            curl --silent --fail "${binaries_archive_download_url}" --output "${local_dir}/${download_file}"
          }
        }
      }
    elif which wget >/dev/null; then
      wget --quiet -P "${local_dir}" "${user_download_url}" || {
        echoerr "trying preferred mirror: ${release_download_url}"
        wget --quiet -P "${local_dir}" "${release_download_url}" || {
          echoerr "falling back to archive: ${archive_download_url}"
          wget --quiet -P "${local_dir}" "${archive_download_url}" || {
            echoerr "must be old archive url: ${binaries_archive_download_url}"
            wget --quiet -P "${local_dir}" "${binaries_archive_download_url}"
          }
        }
      }
    fi
  fi
}

unzipMaven() {
  if [[ ! -d "${local_dir}/apache-maven-${version}" ]]; then
    echoerr "             extracting: ${local_dir}/apache-maven-${version}"
    unzip -o -qq -d "${local_dir}" "${local_dir}/${download_file}"
  fi
}

process_defaults
process_project
process_user_defaults
process_arguments "$@"
make_url "${user_uri}" "${mvn_version}"
debug "maven version: ${mvn_version}"
prepareDirectories

echoerr "Using maven: ${mvn_version}"

downloadMaven
unzipMaven

execRunner "${local_dir}/apache-maven-${version}/bin/mvn" "${mvn_arguments[@]}"
